#%RAML 0.8
title: ExelonUtility_Chatbot_BackendAPI
version: 1.1
baseUri: /mobile/custom/euchatbotapi
protocols: [HTTPS]
/outage/query:
  displayName: Get Outage Status
  get:
    displayName: Outage Status
    description: |
      Endpoint to get outage status
      
    protocols: [HTTPS]
    queryParameters:
      PhoneNumber:
        displayName: Phone Number
        type: string
        required: false
      AccountNumber:
        displayName: Account Number
        type: string
        required: false
/outage:
  displayName: Report Outage
  get:
    displayName: Report Outage
    protocols: [HTTPS]
    queryParameters:
      PhoneNumber:
        displayName: Phone Number
        type: string
        required: false
      AccountNumber:
        displayName: Account Number
        type: string
/bill/lookup:
  displayName: Check Balance
  get:
    protocols: [HTTPS]